const BADGE_DEFINITIONS = [
  // ── Streak Badges ────────────────────────────────────────────────────────────
  {
    slug: 'first-step',
    title: 'First Step',
    description: 'Reach a 1-day streak',
    category: 'streak',
    icon: '👣',
    rarity: 'common',
    requirementType: 'streak_days',
    requirementValue: 1,
    sortOrder: 1,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'consistency-builder',
    title: 'Consistency Builder',
    description: 'Reach a 7-day streak',
    category: 'streak',
    icon: '📅',
    rarity: 'common',
    requirementType: 'streak_days',
    requirementValue: 7,
    sortOrder: 2,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'habit-warrior',
    title: 'Habit Warrior',
    description: 'Reach a 30-day streak',
    category: 'streak',
    icon: '⚔️',
    rarity: 'rare',
    requirementType: 'streak_days',
    requirementValue: 30,
    sortOrder: 3,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'unstoppable',
    title: 'Unstoppable',
    description: 'Reach a 100-day streak',
    category: 'streak',
    icon: '🔥',
    rarity: 'epic',
    requirementType: 'streak_days',
    requirementValue: 100,
    sortOrder: 4,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'legend',
    title: 'Legend',
    description: 'Reach a 365-day streak',
    category: 'streak',
    icon: '🏆',
    rarity: 'mythic',
    requirementType: 'streak_days',
    requirementValue: 365,
    sortOrder: 5,
    rewardType: null,
    rewardValue: null,
  },

  // ── Workout Badges ───────────────────────────────────────────────────────────
  {
    slug: 'first-workout',
    title: 'First Workout',
    description: 'Complete your first verified workout',
    category: 'workout',
    icon: '🏃',
    rarity: 'common',
    requirementType: 'workouts_total',
    requirementValue: 1,
    sortOrder: 6,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'fitness-enthusiast',
    title: 'Fitness Enthusiast',
    description: 'Complete 25 workouts',
    category: 'workout',
    icon: '💪',
    rarity: 'rare',
    requirementType: 'workouts_total',
    requirementValue: 25,
    sortOrder: 7,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'fitness-champion',
    title: 'Fitness Champion',
    description: 'Complete 100 workouts',
    category: 'workout',
    icon: '🏅',
    rarity: 'epic',
    requirementType: 'workouts_total',
    requirementValue: 100,
    sortOrder: 8,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'fitness-legend',
    title: 'Fitness Legend',
    description: 'Complete 500 workouts',
    category: 'workout',
    icon: '🌟',
    rarity: 'mythic',
    requirementType: 'workouts_total',
    requirementValue: 500,
    sortOrder: 9,
    rewardType: null,
    rewardValue: null,
  },

  // ── Academic Badges ──────────────────────────────────────────────────────────
  {
    slug: 'first-quiz',
    title: 'First Quiz',
    description: 'Complete your first verified quiz',
    category: 'academic',
    icon: '📝',
    rarity: 'common',
    requirementType: 'quizzes_total',
    requirementValue: 1,
    sortOrder: 10,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'scholar',
    title: 'Scholar',
    description: 'Complete 25 quizzes',
    category: 'academic',
    icon: '📚',
    rarity: 'rare',
    requirementType: 'quizzes_total',
    requirementValue: 25,
    sortOrder: 11,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'master-scholar',
    title: 'Master Scholar',
    description: 'Complete 100 quizzes',
    category: 'academic',
    icon: '🎓',
    rarity: 'epic',
    requirementType: 'quizzes_total',
    requirementValue: 100,
    sortOrder: 12,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'knowledge-legend',
    title: 'Knowledge Legend',
    description: 'Complete 500 quizzes',
    category: 'academic',
    icon: '🧠',
    rarity: 'mythic',
    requirementType: 'quizzes_total',
    requirementValue: 500,
    sortOrder: 13,
    rewardType: null,
    rewardValue: null,
  },

  // ── Plant Growth Badges ──────────────────────────────────────────────────────
  {
    slug: 'seed-planter',
    title: 'Seed Planter',
    description: 'Plant your first seed',
    category: 'plant',
    icon: '🌱',
    rarity: 'common',
    requirementType: 'has_stake',
    requirementValue: 1,
    sortOrder: 14,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'growing-strong',
    title: 'Growing Strong',
    description: 'Reach the Growing plant stage',
    category: 'plant',
    icon: '🌿',
    rarity: 'rare',
    requirementType: 'plant_stage',
    requirementValue: 2,
    sortOrder: 15,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'mature-gardener',
    title: 'Mature Gardener',
    description: 'Reach the Mature plant stage',
    category: 'plant',
    icon: '🌳',
    rarity: 'epic',
    requirementType: 'plant_stage',
    requirementValue: 3,
    sortOrder: 16,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'master-gardener',
    title: 'Master Gardener',
    description: 'Reach the Fruiting plant stage',
    category: 'plant',
    icon: '🌺',
    rarity: 'legendary',
    requirementType: 'plant_stage',
    requirementValue: 4,
    sortOrder: 17,
    rewardType: null,
    rewardValue: null,
  },

  // ── Staking Badges ───────────────────────────────────────────────────────────
  {
    slug: 'first-commitment',
    title: 'First Commitment',
    description: 'Create your first stake',
    category: 'staking',
    icon: '🔒',
    rarity: 'common',
    requirementType: 'total_staked',
    requirementValue: 0.000001,
    sortOrder: 18,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'committed',
    title: 'Committed',
    description: 'Stake a total of 500 G$',
    category: 'staking',
    icon: '💎',
    rarity: 'rare',
    requirementType: 'total_staked',
    requirementValue: 500,
    sortOrder: 19,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'dedicated',
    title: 'Dedicated',
    description: 'Stake a total of 5,000 G$',
    category: 'staking',
    icon: '👑',
    rarity: 'epic',
    requirementType: 'total_staked',
    requirementValue: 5000,
    sortOrder: 20,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'whale-of-commitment',
    title: 'Whale of Commitment',
    description: 'Stake a total of 25,000 G$',
    category: 'staking',
    icon: '🐋',
    rarity: 'mythic',
    requirementType: 'total_staked',
    requirementValue: 25000,
    sortOrder: 21,
    rewardType: null,
    rewardValue: null,
  },

  // ── Harvest Badges ───────────────────────────────────────────────────────────
  {
    slug: 'first-harvest',
    title: 'First Harvest',
    description: 'Perform your first harvest',
    category: 'harvest',
    icon: '🧺',
    rarity: 'common',
    requirementType: 'total_claimed',
    requirementValue: 0.000001,
    sortOrder: 22,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'fruit-collector',
    title: 'Fruit Collector',
    description: 'Harvest 10 times',
    category: 'harvest',
    icon: '🍎',
    rarity: 'rare',
    requirementType: 'total_claimed',
    requirementValue: 10,
    sortOrder: 23,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: 'master-harvester',
    title: 'Master Harvester',
    description: 'Harvest 100 times',
    category: 'harvest',
    icon: '👨‍🌾',
    rarity: 'epic',
    requirementType: 'total_claimed',
    requirementValue: 100,
    sortOrder: 24,
    rewardType: null,
    rewardValue: null,
  },

  // ── Point Badges ─────────────────────────────────────────────────────────────
  {
    slug: '100-points',
    title: '100 Points Earned',
    description: 'Earn 100 total points',
    category: 'points',
    icon: '⭐',
    rarity: 'common',
    requirementType: 'points_total',
    requirementValue: 100,
    sortOrder: 25,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: '1000-points',
    title: '1000 Points Earned',
    description: 'Earn 1,000 total points',
    category: 'points',
    icon: '🌟',
    rarity: 'rare',
    requirementType: 'points_total',
    requirementValue: 1000,
    sortOrder: 26,
    rewardType: null,
    rewardValue: null,
  },
  {
    slug: '10000-points',
    title: '10000 Points Earned',
    description: 'Earn 10,000 total points',
    category: 'points',
    icon: '💫',
    rarity: 'epic',
    requirementType: 'points_total',
    requirementValue: 10000,
    sortOrder: 27,
    rewardType: null,
    rewardValue: null,
  },
];

function getBadgeDefinitions() {
  return BADGE_DEFINITIONS;
}

function getBadgeBySlug(slug) {
  return BADGE_DEFINITIONS.find((b) => b.slug === slug);
}

module.exports = {
  BADGE_DEFINITIONS,
  getBadgeDefinitions,
  getBadgeBySlug,
};
